<template>
    <section class="block-left">
        <div class="image-content">
            <img src="@/assets/images/bg.jpg" alt="Left Block Image">
        </div>
        <div class="inner-content web-hidden">
            <div class="text-content">
                <h3>Everyday items, we have<br/>something to suit every<br/>occasion.</h3>
                <a href="javascript:;" class="linkline">Shop All Everyday Items</a>
            </div>
        </div>
    </section>
</template>